linters:
  enable:
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - revive
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unused
  disable:
    - errcheck
    - gocognit
    - gocyclo
    - goconst

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  govet:
    # enable or disable analyzers by name
    disable:
      - shadow
