# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - uid: ds_jaeger
    orgId: 1
    name: Jaeger
    type: jaeger
    typeName: Jaeger
    typeLogoUrl: public/app/plugins/datasource/jaeger/img/jaeger_logo.svg
    access: proxy
    url: http://localhost:16686
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData: {}
    readOnly: false
  - uid: ds_loki
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    typeLogoUrl: public/app/plugins/datasource/loki/img/loki_icon.svg
    access: proxy
    url: http://localhost:3100
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData: {}
    readOnly: false
  - uid: ds_prometheus
    orgId: 1
    name: Prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://localhost:9090
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST
    readOnly: false
