{
 "title": "Disks",
 "time": { "from": "2024-11-05T19:37:10.915Z", "to": "2024-11-05T19:37:15.410Z" },
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "label_values(silo_metrics_write_ops,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk ReadOp size",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "silo_metrics_read_ops_size{device=\"device_$Device\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Disk WriteOp size",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "silo_metrics_write_ops_size{device=\"device_$Device\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(silo_metrics_read_ops{device=\"device_$Device\"}[1s])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(silo_metrics_write_ops{device=\"device_$Device\"}[1s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(silo_metrics_read_bytes{device=\"device_$Device\"}[1s])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(silo_metrics_write_bytes{device=\"device_$Device\"}[1s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "ROSOURCE Disk ReadOp size",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "silo_metrics_read_ops_size{device=\"device_rodev_$Device\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ROSOURCE Disk WriteOp size",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "silo_metrics_write_ops_size{device=\"device_rodev_$Device\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "ROSOURCE Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(silo_metrics_read_ops{device=\"device_rodev_$Device\"}[1s])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(silo_metrics_write_ops{device=\"device_rodev_$Device\"}[1s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "ROSOURCE Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(silo_metrics_read_bytes{device=\"device_rodev_$Device\"}[1s])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(silo_metrics_write_bytes{device=\"device_rodev_$Device\"}[1s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "NBD Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(silo_nbd_read_at{device=\"$Device\"}[1s])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(silo_nbd_write_at{device=\"$Device\"}[1s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "NBD Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(silo_nbd_read_at_bytes{device=\"$Device\"}[1s])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(silo_nbd_write_at_bytes{device=\"$Device\"}[1s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Active NBD ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "silo_nbd_active_reads{device=\"$Device\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "silo_nbd_active_writes{device=\"$Device\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(silo_nbd_read_at_time{device=\"$Device\"}[10s])/rate(silo_nbd_read_at{device=\"$Device\"}[10s])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(silo_nbd_write_at_time{device=\"$Device\"}[10s])/rate(silo_nbd_write_at{device=\"$Device\"}[10s])",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}