name: Tests

on:
  pull_request:
    paths-ignore:
      - '.github/signatures/**'

jobs:
  tests:
    runs-on: architect-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Setup nbd
        run: sudo modprobe nbd

      - name: Test
        run: go test -exec sudo -v ./...
        
      - name: Test with Race Conditions
        run: go test -race -v $(go list ./... | grep -v expose)
